// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVpI2kE5WBpu4dgL7IB8iDglGLY2OMm0',
    appId: '1:171534876633:web:221f432b2f16027e7563c8',
    messagingSenderId: '171534876633',
    projectId: 'advancedflutter-b06f1',
    authDomain: 'advancedflutter-b06f1.firebaseapp.com',
    storageBucket: 'advancedflutter-b06f1.firebasestorage.app',
    measurementId: 'G-47KQ9V6Y3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtG5npAPCNj6w15F2zigLodN03HbESJhk',
    appId: '1:171534876633:android:6208b675d2c373d57563c8',
    messagingSenderId: '171534876633',
    projectId: 'advancedflutter-b06f1',
    storageBucket: 'advancedflutter-b06f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb7pgSZI6kq9J2RBSU3icoeBodTZbTTs8',
    appId: '1:171534876633:ios:87703879e28a0da97563c8',
    messagingSenderId: '171534876633',
    projectId: 'advancedflutter-b06f1',
    storageBucket: 'advancedflutter-b06f1.firebasestorage.app',
    iosBundleId: 'com.example.advancedFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb7pgSZI6kq9J2RBSU3icoeBodTZbTTs8',
    appId: '1:171534876633:ios:87703879e28a0da97563c8',
    messagingSenderId: '171534876633',
    projectId: 'advancedflutter-b06f1',
    storageBucket: 'advancedflutter-b06f1.firebasestorage.app',
    iosBundleId: 'com.example.advancedFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOVpI2kE5WBpu4dgL7IB8iDglGLY2OMm0',
    appId: '1:171534876633:web:ed6136501e2a12387563c8',
    messagingSenderId: '171534876633',
    projectId: 'advancedflutter-b06f1',
    authDomain: 'advancedflutter-b06f1.firebaseapp.com',
    storageBucket: 'advancedflutter-b06f1.firebasestorage.app',
    measurementId: 'G-7E3JDZSDZM',
  );

}