# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for firebase distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart"
    release = firebase_app_distribution(
      app: "1:171534876633:android:6208b675d2c373d57563c8",
      firebase_cli_token: ENV["firebase_cli_token"],
      testers: "alikhaled722006@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "Lots of amazing new features to test out!"
  )
  end

end
